// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBRj1cajHR4Dvm-PO9vUZsArvObk3hcxE',
    appId: '1:882871751640:web:cf1a45cf116944096698ad',
    messagingSenderId: '882871751640',
    projectId: 'online-bakeshop',
    authDomain: 'online-bakeshop.firebaseapp.com',
    storageBucket: 'online-bakeshop.firebasestorage.app',
    measurementId: 'G-CVZ8N311NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJxdhd7tQAb0G6aRfTxOLCME_NQRCFJ8',
    appId: '1:882871751640:android:90104f0f1be753fd6698ad',
    messagingSenderId: '882871751640',
    projectId: 'online-bakeshop',
    storageBucket: 'online-bakeshop.firebasestorage.app',
  );
}
